version: '3'

services:
  ui: 
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: weather_ui

  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: weather_db
