FROM postgres:latest

COPY init.sql /docker-entrypoint-initdb.d/init.sql
#COPY db_script.sql /docker-entrypoint-initdb.d/02_db_script.sql

#ENV POSTGRES_USER docker
#ENV POSTGRES_PASSWORD docker
#ENV POSTGRES_DB db_weather



